GET http://localhost:8080/api/courier
Accept: application/json
###

GET http://localhost:8080/api/courier/4
Accept: application/json

###


POST http://localhost:8080/api/courier
Content-Type: application/json

{
  "createdDate": "2021-08-23T14:13:01.323Z[UTC]",
  "createdUserID": 5,
  "firstName": "Húgó",
  "lastName": "Mallo",
  "phoneNumber": "+36704123412"
}

###

PUT http://localhost:8080/api/courier
Content-Type: application/json

{
  "firstName": "Krisztián",
  "id": 8,
  "lastName": "Nagy",
  "phoneNumber": "+36701122333",
  "createdUserID": 5
}

###

DELETE http://localhost:8080/api/courier/2
Accept: application/json

###