GET http://localhost:8080/api/courier
Accept: application/json

###

GET http://localhost:8080/api/courier/1
Accept: application/json

###

DELETE http://localhost:8080/api/courier/4
Accept: application/json

###


POST http://localhost:8080/api/courier
Content-Type: application/json

{
  "firstName": "Sanya",
  "lastName": "Horváth",
  "phoneNumber": "+36306377413"
}
###

PUT http://localhost:8080/api/courier
Content-Type: application/json

{
  "id": 2,
  "createdUser": "USER",
  "firstName": "Hugó",
  "furnitureType": "COURIER",
  "lastName": "Gerics",
  "phoneNumber": "+36200000111"
}

###