GET http://localhost:8080/api/courier
Accept: application/json
###

GET http://localhost:8080/api/courier/3
Accept: application/json

###


POST http://localhost:8080/api/courier
Content-Type: application/json

{
  "createdDate": "2021-08-19T20:49:23.256Z[UTC]",
  "firstName": "Sándor",
  "lastName": "Tóth",
  "phoneNumber": "+36302144123"
}

###

PUT http://localhost:8080/api/courier
Content-Type: application/json

{
  "firstName": "Krisztián",
  "id": 19,
  "lastName": "Nagy",
  "phoneNumber": "+36705566777"
}

###

DELETE http://localhost:8080/api/courier/2
Accept: application/json

###