GET http://localhost:8080/api/furniture
Accept: application/json

###

GET http://localhost:8080/api/furniture/9
Accept: application/json

###

POST http://localhost:8080/api/furniture
Content-Type: application/json

{
  "createdDate": "2021-08-19T20:49:23.256Z[UTC]",
  "description": "Próba leírás",
  "furnitureName": "Szekrény-08",
  "price": 12000
}

###

PUT http://localhost:8080/api/furniture
Content-Type: application/json

{
  "id": 11,
  "createdDate": "2021-08-19T20:49:23.256Z[UTC]",
  "description": "Gardróbként használható, beépíthető",
  "furnitureName": "Szekrény-08",
  "price": 120000
}

###


DELETE http://localhost:8080/api/furniture/2
Accept: application/json

###

