GET http://localhost:8080/api/furniture
Accept: application/json

###

GET http://localhost:8080/api/furniture/7
Accept: application/json

###

DELETE http://localhost:8080/api/furniture/5
Accept: application/json

###


POST http://localhost:8080/api/furniture
Content-Type: application/json

{

}

###

PUT http://localhost:8080/api/furniture
Content-Type: application/json

{
  "id": 1,
  "licencePlateNumber": "ter-666",
  "name": "name-11",
  "onwerID": 1,
  "doorNumbers": 0
}

###